#Question 1
#WAP to Create a 4X2 integer array and print the following Attributes:The shape of an array.
#Array dimensions.The Length of each element of the array in bytes.


In [1]:
import numpy as np

In [2]:
a=np.array([[10,90],[10,100],[20,110],[20,120]])
a

array([[ 10,  90],
       [ 10, 100],
       [ 20, 110],
       [ 20, 120]])

In [3]:
print("Shape of the Array",a.shape)

Shape of the Array (4, 2)


In [4]:
print("Dimentions of the array:",a.ndim)

Dimentions of the array: 2


In [5]:
print("Each item size of the array:",a.itemsize)

Each item size of the array: 4


#Question no 2
#WAP to Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

In [33]:
b=np.arange(10,34,1).reshape(8,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [40]:
b1=np.split(b,(4))
print("4 Sub arrays as fallows:")
b1

4 Sub arrays as fallows:


[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

#Question 3 
#Write a program to show how Numpy taking less memory compared to Python List?

In [41]:
import sys

python_list = list(range(143))
numpy_array = np.arange(143)
list_memory = sum(sys.getsizeof(item) for item in python_list) + sys.getsizeof(python_list)
Numpy_memory = numpy_array.nbytes
print(f"Memory used by python list:{list_memory} bytes")
print(f"Memory used by Numpy array:{Numpy_memory} bytes")

Memory used by python list:5212 bytes
Memory used by Numpy array:572 bytes
